version: '3.8'

services:
  web:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/roblox_api
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - app_next:/app/.next
    working_dir: /app
    command: sh /app/scripts/dev.sh
    
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  app_node_modules:
  app_next: 