version: '3.8'

services:
  web:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/roblox_api
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - next-cache:/app/.next
    command: npm run dev
    
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  node_modules:
  next-cache: 